---
all:
  children:
    linux_agents:
      hosts:
        ubuntu-pc01:
          ansible_host: 192.168.30.43
          observation_domain_id: 2
          capture_interface: ens160

    windows_agents:
      hosts:
        win-pc01:
          ansible_host: 192.168.30.16
          observation_domain_id: 1
          capture_interface: '\Device\NPF_{D546F1DA-D7C8-401D-BED8-3EE6CEADC39B}'
